MelonBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from MelonBlog import settings
from blog import views
import django.views
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry
from django.contrib.sitemaps import GenericSitemap

sitemaps = {
    'blog': GenericSitemap({'queryset': Entry.objects.all(), 'date_field': 'publication_date'}, priority=0.6),
}

urlpatterns = [
    url(r'^$', views.blog, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^mshow/', include('mshow.urls', namespace='mshow')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

blog/urls.py
from django.conf.urls import url
from . import views
from blog.tools import latestentriesfeed


urlpatterns = [
    url(r'^$', views.blog, name="index"),
    url(r'^blog', views.blog, name="blog"),
    url(r'^single/(?P<post_id>[0-9]+)/$', views.single, name="single"),
    url(r'^category/(?P<category_id>[0-9]+)/$',
        views.category, name="category"),
    url(r'^tags/(?P<tag_id>[0-9]+)/$', views.taglist, name="tags"),
    url(r'^bookmark', views.bookmarklist, name="bookmark"),
    url(r'^appcategory/(?P<appcategory_id>[0-9]+)/$',
        views.appcategory, name="appcategory"),
    url(r'^contact', views.contact, name="contact"),
    url(r'^sendmail', views.sendmail, name="sendmail"),
    url(r'^latest/feed/$', latestentriesfeed.LatestEntriesFeed(),
        name="latestentriesfeed"),
    url(r'^crawler', views.crawler, name="crawler"),
    url(r'^tools', views.tools, name="tools"),
    url(r'^readdoc', views.readdoc, name="readdoc"),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from tagging.fields import TagField

# Create your models here.


class Category(models.Model):
    title = models.CharField("title", max_length=255)
    slug = models.SlugField("slug", unique=True, max_length=255,
                            help_text="Used to build the catagory's URL.")
    description = models.TextField("description", blank=True)
    # the TreeForignKey need to install the mptt package and import it , after to import it .
# parent = TreeForignKey('self', relate_name='children', null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_('parent catagory'))

    def __unicode__(self):
        return self.title


class Entry(models.Model):

    STATUS_CHOICES = ((0, 'draft'), (1, 'hidden'), (2, 'publish'))
    title = models.CharField("title", max_length=255)
    blog_abstract = models.TextField(
        "blog abstract", null=True, blank=True, max_length=200)
    slug = models.CharField("slug", max_length=255)
    status = models.IntegerField(
        "status", db_index=True, choices=STATUS_CHOICES, default=0)
    publication_date = models.DateTimeField(
        "publication date", db_index=True, default=timezone.now, help_text="Used to build the entry's URL.")
    start_publication = models.DateTimeField(
        "start publication", db_index=True, blank=True, null=True, help_text="Start date of publication.")
    end_publication = models.DateTimeField(
        "end publication", db_index=True, blank=True, null=True, help_text="End date of publication.")
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    last_update = models.DateTimeField("last update", default=timezone.now)
    # content
    content = models.TextField("content", null=True, blank=True)
    # after to convert the content to html or markdown modle. add some method
    categorys = models.ManyToManyField(
        Category, blank=True, related_name="entries", verbose_name="categories")

    tags = TagField()
    head_image_url = models.URLField(
        "head image url", max_length=255, null=True, blank=True)
    head_image = models.ImageField(
        upload_to='photos/%Y/%m', null=True, blank=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/blog/single/%i/" % self.id


class BookmarkCategory(models.Model):

    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    description = models.CharField(
        "description", null=True, blank=True, max_length=500)

    def __unicode__(self):
        return self.title


class Bookmark(models.Model):

    STATUS_CHOICES = ((0, 'draft'), (1, 'hidden'), (2, 'publish'))
    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    description = models.TextField(
        "description", null=True, blank=True, max_length=320)
    status = models.IntegerField(
        "status", db_index=True, choices=STATUS_CHOICES, default=2)
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    click_times = models.IntegerField("click_times", default=0)
    url = models.URLField("url", max_length=512, null=True, blank=True)
    categorys = models.ForeignKey(BookmarkCategory, blank=True)
    widthfield = models.IntegerField('widthfiled', default=400)
    heightfield = models.IntegerField('heightfield', default=400)
    head_image = models.ImageField(
        upload_to='bookmarks/%Y/%m', width_field='widthfield', height_field='heightfield', null=True, blank=True)

    def __unicode__(self):
        return self.title


class AppCategory(models.Model):
    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    description = models.CharField(
        "description", null=True, blank=True, max_length=500)

    def __unicode__(self):
        return self.title


class AppEntry(models.Model):
    STATUS_CHOICES = ((0, 'draft'), (1, 'hidden'), (2, 'publish'))
    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    app_abstract = models.CharField("abstract", max_length=64)
    description = models.TextField(
        "description", null=True, blank=True, max_length=320)
    status = models.IntegerField(
        "status", db_index=True, choices=STATUS_CHOICES, default=2)
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    click_times = models.IntegerField("click_times", default=0)
    url = models.URLField("url", max_length=512, null=True, blank=True)
    categorys = models.ForeignKey(AppCategory, related_name="appentry")

    def __unicode__(self):
        return self.title

mshow/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.

ACTION_METHOD = (
        ('pt-page-moveToLeft', 'pt-page-moveToLeft'),
        ('pt-page-moveFromLeft', 'pt-page-moveFromLeft'),
        ('pt-page-moveToRight', 'pt-page-moveToRight'),
        ('pt-page-moveFromRight', 'pt-page-moveFromRight'),
        ('pt-page-moveToTop', 'pt-page-moveToTop'),
        ('pt-page-moveFromTop', 'pt-page-moveFromTop'),
        ('pt-page-moveToBottom', 'pt-page-moveToBottom'),
        ('pt-page-moveFromBottom', 'pt-page-moveFromBottom'),
        ('pt-page-moveToLeftFade', 'pt-page-moveToLeftFade'),
        ('pt-page-moveFromLeftFade', 'pt-page-moveFromLeftFade'),
        ('pt-page-moveToRightFade', 'pt-page-moveToRightFade'),
        ('pt-page-moveFromRightFade', 'pt-page-moveFromRightFade'),
        ('pt-page-moveToTopFade', 'pt-page-moveToTopFade'),
        ('pt-page-moveFromTopFade', 'pt-page-moveFromTopFade'),
        ('pt-page-moveToBottomFade', 'pt-page-moveToBottomFade'),
        ('pt-page-moveFromBottomFade', 'pt-page-moveFromBottomFade'),
        ('pt-page-moveToLeftEasing', 'pt-page-moveToLeftEasing'),
        ('pt-page-moveToRightEasing', 'pt-page-moveToRightEasing'),
        ('pt-page-moveToTopEasing', 'pt-page-moveToTopEasing'),
        ('pt-page-moveToBottomEasing', 'pt-page-moveToBottomEasing'),
        ('pt-page-moveIconUp', 'pt-page-moveIconUp'),
        ('pt-page-moveCircle', 'pt-page-moveCircle'),
        ('pt-page-scaleDown', 'pt-page-scaleDown'),
        ('pt-page-scaleUp', 'pt-page-scaleUp'),
        ('pt-page-scaleUpDown', 'pt-page-scaleUpDown'),
        ('pt-page-scaleDownUp', 'pt-page-scaleDownUp'),
        ('pt-page-scaleDownCenter', 'pt-page-scaleDownCenter'),
        ('pt-page-scaleUpCenter', 'pt-page-scaleUpCenter'),
        ('pt-page-rotateRightSideFirst', 'pt-page-rotateRightSideFirst'),
        ('pt-page-rotateLeftSideFirst', 'pt-page-rotateLeftSideFirst'),
        ('pt-page-rotateTopSideFirst', 'pt-page-rotateTopSideFirst'),
        ('pt-page-rotateBottomSideFirst', 'pt-page-rotateBottomSideFirst'),
        ('pt-page-flipOutRight', 'pt-page-flipOutRight'),
        ('pt-page-flipInLeft', 'pt-page-flipInLeft'),
        ('pt-page-flipOutLeft', 'pt-page-flipOutLeft'),
        ('pt-page-flipInRight', 'pt-page-flipInRight'),
        ('pt-page-flipOutTop', 'pt-page-flipOutTop'),
        ('pt-page-flipInBottom', 'pt-page-flipInBottom'),
        ('pt-page-flipOutBottom', 'pt-page-flipOutBottom'),
        ('pt-page-flipInTop', 'pt-page-flipInTop'),
        ('pt-page-rotateFall', 'pt-page-rotateFall'),
        ('pt-page-rotateOutNewspaper', 'pt-page-rotateOutNewspaper'),
        ('pt-page-rotateInNewspaper', 'pt-page-rotateInNewspaper'),
        ('pt-page-rotatePushLeft', 'pt-page-rotatePushLeft'),
        ('pt-page-rotatePushRight', 'pt-page-rotatePushRight'),
        ('pt-page-rotatePushTop', 'pt-page-rotatePushTop'),
        ('pt-page-rotatePushBottom', 'pt-page-rotatePushBottom'),
        ('pt-page-rotatePullRight', 'pt-page-rotatePullRight'),
        ('pt-page-rotatePullLeft', 'pt-page-rotatePullLeft'),
        ('pt-page-rotatePullTop', 'pt-page-rotatePullTop'),
        ('pt-page-rotatePullBottom', 'pt-page-rotatePullBottom'),
        ('pt-page-rotateFoldRight', 'pt-page-rotateFoldRight'),
        ('pt-page-rotateFoldLeft', 'pt-page-rotateFoldLeft'),
        ('pt-page-rotateFoldTop', 'pt-page-rotateFoldTop'),
        ('pt-page-rotateFoldBottom', 'pt-page-rotateFoldBottom'),
        ('pt-page-rotateUnfoldLeft', 'pt-page-rotateUnfoldLeft'),
        ('pt-page-rotateUnfoldRight', 'pt-page-rotateUnfoldRight'),
        ('pt-page-rotateUnfoldTop', 'pt-page-rotateUnfoldTop'),
        ('pt-page-rotateUnfoldBottom', 'pt-page-rotateUnfoldBottom'),
        ('pt-page-rotateRoomLeftOut', 'pt-page-rotateRoomLeftOut'),
        ('pt-page-rotateRoomLeftIn', 'pt-page-rotateRoomLeftIn'),
        ('pt-page-rotateRoomRightOut', 'pt-page-rotateRoomRightOut'),
        ('pt-page-rotateRoomRightIn', 'pt-page-rotateRoomRightIn'),
        ('pt-page-rotateRoomTopOut', 'pt-page-rotateRoomTopOut'),
        ('pt-page-rotateRoomTopIn', 'pt-page-rotateRoomTopIn'),
        ('pt-page-rotateRoomBottomOut', 'pt-page-rotateRoomBottomOut'),
        ('pt-page-rotateRoomBottomIn', 'pt-page-rotateRoomBottomIn'),
        ('pt-page-rotateCubeLeftOut', 'pt-page-rotateCubeLeftOut'),
        ('pt-page-rotateCubeLeftIn', 'pt-page-rotateCubeLeftIn'),
        ('pt-page-rotateCubeRightOut', 'pt-page-rotateCubeRightOut'),
        ('pt-page-rotateCubeRightIn', 'pt-page-rotateCubeRightIn'),
        ('pt-page-rotateCubeTopOut', 'pt-page-rotateCubeTopOut'),
        ('pt-page-rotateCubeTopIn', 'pt-page-rotateCubeTopIn'),
        ('pt-page-rotateCubeBottomOut', 'pt-page-rotateCubeBottomOut'),
        ('pt-page-rotateCubeBottomIn', 'pt-page-rotateCubeBottomIn'),
        ('pt-page-rotateCarouselLeftOut', 'pt-page-rotateCarouselLeftOut'),
        ('pt-page-rotateCarouselLeftIn', 'pt-page-rotateCarouselLeftIn'),
        ('pt-page-rotateCarouselRightOut', 'pt-page-rotateCarouselRightOut'),
        ('pt-page-rotateCarouselRightIn', 'pt-page-rotateCarouselRightIn'),
        ('pt-page-rotateCarouselTopOut', 'pt-page-rotateCarouselTopOut'),
        ('pt-page-rotateCarouselTopIn', 'pt-page-rotateCarouselTopIn'),
        ('pt-page-rotateCarouselBottomOut', 'pt-page-rotateCarouselBottomOut'),
        ('pt-page-rotateCarouselBottomIn', 'pt-page-rotateCarouselBottomIn'),
        ('pt-page-rotateSidesOut', 'pt-page-rotateSidesOut'),
        ('pt-page-rotateSidesIn', 'pt-page-rotateSidesIn'),
        ('pt-page-rotateSlideOut', 'pt-page-rotateSlideOut'),
        ('pt-page-rotateSlideIn', 'pt-page-rotateSlideIn'),
    )

class MobileShow(models.Model):
    name = models.CharField("name", max_length=255)
    description = models.TextField("description", null=True, blank=True)
    publication_date = models.DateTimeField("publication date", db_index=True, default=timezone.now, help_text="Used to build the entry's URL.")
    start_publication = models.DateTimeField("start publication", db_index=True, blank=True, null=True, help_text="Start date of publication.")
    end_publication = models.DateTimeField("end publication", db_index=True, blank=True, null=True, help_text="End date of publication.")
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    last_update = models.DateTimeField("last update", default=timezone.now)
    
    def __unicode__(self):
        return self.name
    
class Page(models.Model):
    name = models.CharField("name", max_length=255)
    PAGE_ATTR = (
        ('page-cuttent','page-current'),          
        ('hide','hide'),
    )
    attribute = models.CharField("attribute",max_length=50,choices=PAGE_ATTR)
    mobile_show = models.ForeignKey(MobileShow)
    
    def __unicode__(self):
        return self.name
    
class ContentImg(models.Model):
    name = models.CharField("name", max_length=255)
    action = models.CharField("action",max_length=50, choices=ACTION_METHOD)
    image = models.ImageField(upload_to='mshow/%Y/%m', null=True, blank=True)
    page = models.ForeignKey(Page)
    
    def __unicode__(self):
        return self.name
    
class ContentText(models.Model):
    name = models.CharField("name", max_length=255)
    action = models.CharField(max_length=50, choices=ACTION_METHOD)
    description = models.TextField("description", null=True, blank=True)
    page = models.ForeignKey(Page)
    
    def __unicode__(self):
        return self.name
    
    
    

blog/templates/blog.html
{% extends "common/base_blog.html" %}
{% load staticfiles %}
{% load i18n %}

{% block headcontent %}
	<meta charset="utf-8" />
	<title>william's blog| 云计算、大数据、java、Python</title>
    <meta name="robots" content="index, follow" />
    <meta name="keywords" content="云计算,大数据,人工智能,虚拟化,java,python,ITIL,运维,ansible,openstack,docker,运维自动化,云数据中心" />
    <meta name="description" content="云计算,大数据,人工智能,虚拟化,java,python,ITIL,运维,ansible,openstack,docker" />
	<meta name="author" content="william" />
{% endblock %}

{% block maincontent %}
    <section class="content">
	
    	{% if latest_entry_list %}
    		{% for entry in latest_entry_list %}
    		
    	<article class="post">
            <div class="date-wrapper"> 
				<div class="date-value">{{ entry.publication_date.day }}</div>
                <div class="month-value">{{ entry.publication_date|date:"M"}}</div>
            </div>
        	<div class="header-wrapper">
                <h2 class="posttitle"><a href="{% url 'blog:single' entry.id %}">{{entry.title}}</a></h2>
                <div class="entry-utility">
                    <div class="user">Posted by <a href="#">william</a></div> <div class="tag">Tags: 
                    <a href="#">
                    {{entry.tags}}
                    </a>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            {% if entry.head_image %}
            <div class="postimg">
                <img src="{{MEDIA_URL}}{{entry.head_image}}" alt="" />
            </div>
   			{% endif %}
            <div class="entry-content">
            	{{ entry.blog_abstract }}
				<a href="{% url 'blog:single' entry.id %}" class="more">{% trans 'more' %} &rarr;</a>
            </div>
           
            <div class="clear"></div>
        </article>
    		{% endfor %}
    	{% endif %}
    	
    	<div class="wp-pagenavi">
			<span class="step-links">
		    	<span class="pages">
					Page {{ latest_entry_list.number }} of {{ latest_entry_list.paginator.num_pages }}
				</span>

				{% if latest_entry_list.has_previous %}
					<a href="?page={{ latest_entry_list.previous_page_number }}">{% trans 'previous' %}</a>
				{% endif %}

				{% for pagenum in latest_entry_list.paginator.page_range %}
					{% if pagenum == latest_entry_list.number %}
						<span class="current"><span>{{ pagenum }}</span></span>
					{% else %}
						<a class="page" href="?page={{ pagenum }}">{{ pagenum }}</a>
						{% endif %}
				{% endfor %}

				{% if latest_entry_list.has_next %}
					<a href="?page={{ latest_entry_list.next_page_number }}">{% trans 'next' %}</a>
				{% endif %}
			</span>
		</div>
    </section>
{% endblock %}
 

blog/templates/contact.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
{% block head %}
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8" />
	<title>联系我 | 云计算、大数据、java、Python</title>
    <meta name="robots" content="index, follow" />
    <meta name="keywords" content="云计算,大数据,人工智能,虚拟化,java,python,ITIL,运维,ansible,openstack,docker,运维自动化,云数据中心" />
    <meta name="description" content="云计算,大数据,人工智能,虚拟化,java,python,ITIL,运维,ansible,openstack,docker" />
	<meta name="author" content="william" />

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    

	<!-- CSS
  ================================================== -->
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/inner.css' %}" />    
    <link rel="stylesheet" href="{% static 'styles/color.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/layout.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/flexslider.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/prettyPhoto.css' %}"  media="screen" />
    

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

    
    
</head>

{% endblock %}


{% block content %}
        
        <!-- BEFORE CONTENT -->
        <div id="outerbeforecontent">
        	<div class="container">
            <div class="row">
                <div id="beforecontent" class="twelve columns">
                
                    <h1 class="pagetitle">{% trans 'Contact us' %}</h1>
                    <span class="pagedesc">{% trans 'Contact us abstract' %}</span>
                    
                    <a href="#" class="button">{% trans 'Contact us' %}</a>
                    
                </div>
            </div>
            </div>
        </div>
        <!-- END BEFORE CONTENT -->


        <!-- MAIN CONTENT -->
        <div id="outermain">
        	<div class="container">
                <div class="row">
           
                    <section id="maincontent" class="eight columns positionleft">
                    	<div class="padcontent">

                            <section class="content">
                            
                            	<h2>{% trans 'Keep in Touch with me' %} </h2>
                            	<p>QQ: 59170121</p>
                            	<p>wechat: yourwilliam</p>
                            	<p>twitter: william valentine</p>
                            	<p>email: yourwilliam@gmail.com</p>
                            	<p>github: <a href="https://github.com/yourwilliam/">https://github.com/yourwilliam/</a></p>
                            	
                                
                                <div class="separator"></div>
                                
                                <h3>{% trans 'Send me a Message' %}</h3>
                                <p>{% trans 'welcome message' %}</p>
                            
                                <div id="contactform">
                                <form id="contact" action="{% url 'blog:sendmail' %}" method="post">
                                  <fieldset>
                                  	 {% csrf_token %}
                                      <span class="error" id="name_error">Please enter name !</span>
                                      <span class="error" id="email_error">Please enter email address !</span>
                                      <span class="error" id="email_error2">Please enter valid email address !</span>
                                      <span class="error" id="msg_error">Please enter message !</span>
                                      <label for="name" id="name_label">Name (required)</label>
                                      <input type="text" name="name" id="name" size="50" value="" class="text-input" />
                                      <label for="email" id="email_label">Email (required)</label>
                                      <input type="text" name="email" id="email" size="50" value="" class="text-input" />
                                      <label for="subject" id="subject_label">Subject</label>
                                      <input type="text" name="subject" id="subject" size="50"  value="" class="text-input" />
                                      <label for="msg" id="msg_label">Message</label>
                                      <textarea rows="10" name="msg" id="msg" class="text-input"></textarea>
                                      <br />
                                      <input type="submit" name="submit" class="button" id="submit_btn" value="Send Message"/>
                                  </fieldset>
                                </form>
                                <div class="clear"></div>
                                </div><!-- end contactform -->
                         
                                <div class="separator"></div>
                                
                                <h3>Find me</h3>
                                
                                
                            </section>
                         
                        </div>
                    </section>
                    
                   {% block sidebar %}
                    <aside id="sidebar" class="four columns">
                    	<div class="padsidebar">
                        <ul>
                            <li class="widget-container">
                                <h2 class="widget-title">{% trans 'Search' %}</h2>
                                <form action="#" id="searchform" method="get">
                                    <div class="bgsearch">
                                    <input type="text" value="" id="s" name="s"> 
                                    <input type="submit" value="" class="searchbutton">
                                    </div>
                                </form>
                            </li>
                            <li class="widget-container">
                                <h2 class="widget-title">{% trans 'Categories' %}</h2>
                                <ul>
                                {% for category in catagory_list %}
                                	<li><a href="{% url 'blog:category' category.id %}">{{ category.title }}({{ category.entrynum }})</a></li>
                                {% endfor %}
                                </ul>
                            </li>
                            <li class="widget-container">
                                <h2 class="widget-title">{% trans 'Latest Post' %}</h2>
                                <ul class="rp-widget">
                                	{% for post in latest_post %}
                                		<li>
		                                    <div class="postimg"><img src="{% static 'images/content/lp1.gif' %}" alt="" /></div>
		                                    <h3><a href="{% url 'blog:single' post.id %}">{{ post.title }}</a></h3>
		                                    <span class="smalldate">{{ post.publication_date }}</span>
		                                    <span class="clear"></span>
                                    </li>
                                	{% endfor %}
                                </ul>
                            </li>
                        </ul>
                        <div id="tagsList">
                        <h2 class="widget-title">{% trans 'Tag list' %}</h2>
                        {% for tag in tag_list %}
                        	<span><a href="{% url 'blog:tags' tag.id %}">{{ tag.name }}</a></span>
                        {% endfor %}
						</div>
	                  </div>
                    </aside>
               		{% endblock %}  
                 
                </div>
            </div>
        </div>
        <!-- END MAIN CONTENT -->
{% endblock %}        

{% block javascript %}
<!-- ////////////////////////////////// -->
<!-- //      Javascript Files        // -->
<!-- ////////////////////////////////// -->
<script type="text/javascript" src="{% static 'js/jquery-1.7.1.min.js' %}"></script>

<!-- jQuery Superfish -->
<script type="text/javascript" src="{% static 'js/hoverIntent.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/superfish.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/supersubs.js' %}"></script>


<!-- jQuery Dropdown Mobile -->
<script type="text/javascript" src="{% static 'js/tinynav.min.js' %}"></script>

<!-- Custom Script -->
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

<!-- Form Contact Script -->
<script type="text/javascript" src="{% static 'js/contact.js' %}"></script>

<!-- Custom Script -->
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<script type="text/javascript" src="{% static 'js/tagcloud.js' %}"></script>


{% endblock %}