MelonBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from MelonBlog import settings
from blog import views
import django.views
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry
from django.contrib.sitemaps import GenericSitemap

sitemaps = {
    'blog': GenericSitemap({'queryset': Entry.objects.all(), 'date_field': 'publication_date'}, priority=0.6),
}

urlpatterns = [
    url(r'^$', views.blog, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^mshow/', include('mshow.urls', namespace='mshow')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

blog/urls.py
from django.conf.urls import url
from . import views
from blog.tools import latestentriesfeed


urlpatterns = [
    url(r'^$', views.blog, name="index"),
    url(r'^blog', views.blog, name="blog"),
    url(r'^single/(?P<post_id>[0-9]+)/$', views.single, name="single"),
    url(r'^category/(?P<category_id>[0-9]+)/$',
        views.category, name="category"),
    url(r'^tags/(?P<tag_id>[0-9]+)/$', views.taglist, name="tags"),
    url(r'^bookmark', views.bookmarklist, name="bookmark"),
    url(r'^appcategory/(?P<appcategory_id>[0-9]+)/$',
        views.appcategory, name="appcategory"),
    url(r'^contact', views.contact, name="contact"),
    url(r'^sendmail', views.sendmail, name="sendmail"),
    url(r'^latest/feed/$', latestentriesfeed.LatestEntriesFeed(),
        name="latestentriesfeed"),
    url(r'^crawler', views.crawler, name="crawler"),
    url(r'^tools', views.tools, name="tools"),
    url(r'^readdoc', views.readdoc, name="readdoc"),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from tagging.fields import TagField

# Create your models here.


class Category(models.Model):
    title = models.CharField("title", max_length=255)
    slug = models.SlugField("slug", unique=True, max_length=255,
                            help_text="Used to build the catagory's URL.")
    description = models.TextField("description", blank=True)
    # the TreeForignKey need to install the mptt package and import it , after to import it .
# parent = TreeForignKey('self', relate_name='children', null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_('parent catagory'))

    def __unicode__(self):
        return self.title


class Entry(models.Model):

    STATUS_CHOICES = ((0, 'draft'), (1, 'hidden'), (2, 'publish'))
    title = models.CharField("title", max_length=255)
    blog_abstract = models.TextField(
        "blog abstract", null=True, blank=True, max_length=200)
    slug = models.CharField("slug", max_length=255)
    status = models.IntegerField(
        "status", db_index=True, choices=STATUS_CHOICES, default=0)
    publication_date = models.DateTimeField(
        "publication date", db_index=True, default=timezone.now, help_text="Used to build the entry's URL.")
    start_publication = models.DateTimeField(
        "start publication", db_index=True, blank=True, null=True, help_text="Start date of publication.")
    end_publication = models.DateTimeField(
        "end publication", db_index=True, blank=True, null=True, help_text="End date of publication.")
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    last_update = models.DateTimeField("last update", default=timezone.now)
    # content
    content = models.TextField("content", null=True, blank=True)
    # after to convert the content to html or markdown modle. add some method
    categorys = models.ManyToManyField(
        Category, blank=True, related_name="entries", verbose_name="categories")

    tags = TagField()
    head_image_url = models.URLField(
        "head image url", max_length=255, null=True, blank=True)
    head_image = models.ImageField(
        upload_to='photos/%Y/%m', null=True, blank=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/blog/single/%i/" % self.id


class BookmarkCategory(models.Model):

    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    description = models.CharField(
        "description", null=True, blank=True, max_length=500)

    def __unicode__(self):
        return self.title


class Bookmark(models.Model):

    STATUS_CHOICES = ((0, 'draft'), (1, 'hidden'), (2, 'publish'))
    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    description = models.TextField(
        "description", null=True, blank=True, max_length=320)
    status = models.IntegerField(
        "status", db_index=True, choices=STATUS_CHOICES, default=2)
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    click_times = models.IntegerField("click_times", default=0)
    url = models.URLField("url", max_length=512, null=True, blank=True)
    categorys = models.ForeignKey(BookmarkCategory, blank=True)
    widthfield = models.IntegerField('widthfiled', default=400)
    heightfield = models.IntegerField('heightfield', default=400)
    head_image = models.ImageField(
        upload_to='bookmarks/%Y/%m', width_field='widthfield', height_field='heightfield', null=True, blank=True)

    def __unicode__(self):
        return self.title


class AppCategory(models.Model):
    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    description = models.CharField(
        "description", null=True, blank=True, max_length=500)

    def __unicode__(self):
        return self.title


class AppEntry(models.Model):
    STATUS_CHOICES = ((0, 'draft'), (1, 'hidden'), (2, 'publish'))
    title = models.CharField("title", max_length=255)
    slug = models.CharField("slug", max_length=255)
    app_abstract = models.CharField("abstract", max_length=64)
    description = models.TextField(
        "description", null=True, blank=True, max_length=320)
    status = models.IntegerField(
        "status", db_index=True, choices=STATUS_CHOICES, default=2)
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    click_times = models.IntegerField("click_times", default=0)
    url = models.URLField("url", max_length=512, null=True, blank=True)
    categorys = models.ForeignKey(AppCategory, related_name="appentry")

    def __unicode__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from blog.models import Entry, Category, Bookmark, BookmarkCategory, AppCategory, \
    AppEntry
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from tagging.models import Tag
from django.core.mail import send_mail

from bs4 import BeautifulSoup

from docx import Document

import xlwt
from django.http import StreamingHttpResponse

import requests


# Create your views here.
def index(request):
    latest_entry_list = Entry.objects.order_by('creation_date')[:10]
    context = {'latest_entry_list': latest_entry_list}
    return render(request, 'index.html', context)


def blog(request):
    latest_entry_list = Entry.objects.order_by('-creation_date')
    paginator = Paginator(latest_entry_list, 10)
    page = request.GET.get('page')

    try:
        entrys = paginator.page(page)
    except PageNotAnInteger:
        entrys = paginator.page(1)
    except EmptyPage:
        entrys = paginator.page(paginator.num_pages)

    catagory_list = Category.objects.raw(
        "select cate.id, cate.title, cate.description, count(cate.id) as entrynum from blog_category as cate, blog_entry_categorys as enca where cate.id = enca.category_id group by cate.id")

    tag_list = Tag.objects.all()

    context = {'latest_entry_list': entrys, 'catagory_list': catagory_list,
               'latest_post': latest_entry_list[:3], 'tag_list': tag_list}

    return render(request, 'blog.html', context)


def single(request, post_id):
    # post_id = request.GET.get('id')
    post = Entry.objects.get(id=post_id)

    latest_entry_list = Entry.objects.order_by('-creation_date')[:3]
    catagory_list = Category.objects.raw(
        "select cate.id, cate.title, cate.description, count(cate.id) as entrynum from blog_category as cate, blog_entry_categorys as enca where cate.id = enca.category_id group by cate.id")
    tag_list = Tag.objects.all()

    context = {'post': post, 'catagory_list': catagory_list,
               'latest_post': latest_entry_list, 'tag_list': tag_list}
    return render(request, 'single.html', context)


def category(request, category_id):
    cate_entry_list = Entry.objects.filter(
        categorys__id=category_id).order_by('-creation_date')

    paginator = Paginator(cate_entry_list, 10)
    page = request.GET.get('page')

    try:
        entrys = paginator.page(page)
    except PageNotAnInteger:
        entrys = paginator.page(1)
    except EmptyPage:
        entrys = paginator.page(paginator.num_pages)

    latest_entry_list = Entry.objects.order_by('-creation_date')[:3]
    catagory_list = Category.objects.raw(
        "select cate.id, cate.title, cate.description, count(cate.id) as entrynum from blog_category as cate, blog_entry_categorys as enca where cate.id = enca.category_id group by cate.id")
    tag_list = Tag.objects.all()

    context = {'latest_entry_list': entrys, 'catagory_list': catagory_list,
               'latest_post': latest_entry_list, 'tag_list': tag_list}

    return render(request, 'blog.html', context)


def taglist(request, tag_id):

    tag = Tag.objects.get(id=tag_id)
    tag_entry_list = Entry.objects.filter(tags__icontains=tag.name)
    paginator = Paginator(tag_entry_list, 10)
    page = request.GET.get('page')

    try:
        entrys = paginator.page(page)
    except PageNotAnInteger:
        entrys = paginator.page(1)
    except EmptyPage:
        entrys = paginator.page(paginator.num_pages)

    latest_entry_list = Entry.objects.order_by('-creation_date')[:3]
    catagory_list = Category.objects.raw(
        "select cate.id, cate.title, cate.description, count(cate.id) as entrynum from blog_category as cate, blog_entry_categorys as enca where cate.id = enca.category_id group by cate.id")
    tag_list = Tag.objects.all()

    context = {'latest_entry_list': entrys, 'catagory_list': catagory_list,
               'latest_post': latest_entry_list, 'tag_list': tag_list}

    return render(request, 'blog.html', context)


def bookmarklist(request):

    bookmarks = Bookmark.objects.raw(
        "select book.id, book.title, book.description, book.click_times, book.url, book.head_image, cate.title as category_title from blog_bookmark as book, blog_bookmarkcategory as cate where book.categorys_id = cate.id and book.status = 2")

    categorys = BookmarkCategory.objects.all()
    context = {'bookmark_list': bookmarks, 'category_list': categorys}
    return render(request, 'bookmark.html', context)


def appcategory(request, appcategory_id):
    appcategory = AppCategory.objects.get(id=appcategory_id)
    applist = AppEntry.objects.filter(categorys_id=appcategory_id)
    context = {'appcategory': appcategory, 'applist': applist}
    return render(request, 'service.html', context)


def contact(request):
    latest_entry_list = Entry.objects.order_by('-creation_date')[:3]
    catagory_list = Category.objects.raw(
        "select cate.id, cate.title, cate.description, count(cate.id) as entrynum from blog_category as cate, blog_entry_categorys as enca where cate.id = enca.category_id group by cate.id")
    tag_list = Tag.objects.all()
    context = {'catagory_list': catagory_list,
               'latest_post': latest_entry_list, 'tag_list': tag_list}

    return render(request, 'contact.html', context)


def sendmail(request):
    name = request.POST.get('name', 'customer')
    email = request.POST.get('email', 'melonblogs@163.com')
    subject = request.POST.get('subject')
    msg = request.POST.get('msg')
    msg = 'name:' + name + 'from email:' + email + 'subject:' + msg

    send_mail(subject, msg, 'melonblogs@163.com', [
              '59170121@qq.com'], fail_silently=False)
    return render(request, 'contact.html')


def crawler(request):
    print "Hello Beautiful!"

    base_url = "http://www.searchcio.com.cn/"
    campaigns = "news.htm"

    print "Starting at url: " + base_url + campaigns

    # Fetch page from the web and get the text response
    r = requests.get(base_url + campaigns)
    data = r.text

    print "Retrived data, getting campaign links."
    # Parse it into a format we can handle
    soup = BeautifulSoup(data, "html.parser")
    # Get the main div.
    main_div = soup.find('div', {'id': 'main'})

    # pre define the
    dict_list = []
    width = 0

    # loop over all the links
    for a in main_div.findAll('a'):
        print a
#        dict = {'href': u"" + a['href'], 'desc': u"" + a.find('img')['alt']}
        dict = {'href': u"" + a['href']}
        width = max(len(dict['href']), width)
        dict_list.append(dict)

    # Show the results just for nice print
    print ""
    print "Found %d items." % len(dict_list)
    for l in dict_list:
        print '{message: <{width}}'.format(message=l['desc'].encode('utf8'), width=width) + "\t" + l['href'].encode('utf8')

    print ""
    # Process...
    for l in dict_list:
        if not "produkt" in l['href'].encode('utf8'):
            continue
        processProduct(base_url, l)


def tools(request):

    latest_entry_list = Entry.objects.order_by('-creation_date')[:3]
    catagory_list = Category.objects.raw(
        "select cate.id, cate.title, cate.description, count(cate.id) as entrynum from blog_category as cate, blog_entry_categorys as enca where cate.id = enca.category_id group by cate.id")
    tag_list = Tag.objects.all()
    context = {'catagory_list': catagory_list,
               'latest_post': latest_entry_list, 'tag_list': tag_list}

    return render(request, 'tools.html', context)


def readdoc(request):

    print('124125')

    wordfile = request.FILES['wordfile']

    with open('/Users/valentine/Downloads/readbook1.docx', 'wb+') as destination:
        for chunk in wordfile.chunks():
            destination.write(chunk)

    document = Document(u'/Users/valentine/Downloads/readbook1.docx')
    # listp = [paragraph.text.encode('gb2312') for paragraph in document.paragraphs]

    counters = {}
    listp = document.paragraphs
    for i in listp:
        # print i.text
        items = i.text.split(' ')
        for item in items:
            if item in counters:
                counters[item] += 1
            else:
                counters[item] = 1

    # print "count of different word:"
    # print counters

    data = xlwt.Workbook()
    table = data.add_sheet('name', cell_overwrite_ok=True)
    line = 0
    for (k, v) in counters.items():
        print k, v
        table.write(line, 0, k)
        table.write(line, 1, v)
        line += 1

    data.save(u'/Users/valentine/Downloads/test3.xls')

    # print "Most popular word:"
    # print sorted([(counter,word) for word,counter in counters.items()],reverse=True)[0][1]

    def file_iterator(file_name, chunk_size=512):
        with open(file_name) as f:
            while True:
                c = f.read(chunk_size)
                if c:
                    yield c
                else:
                    break

    the_file_name = "test3.xls"
    response = StreamingHttpResponse(file_iterator(u'/Users/valentine/Downloads/test3.xls'))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{0}"'.format(the_file_name)

    return response

blog/templates/common/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
{% block head %}
<head>

	<!-- Basic Page Needs
  ================================================== -->
  {% block headcontent %}
	<meta charset="utf-8" />
	<title>amazing</title>
    <meta name="robots" content="index, follow" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
	<meta name="author" content="" />
  {% endblock %}
	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

	<!-- 新 Bootstrap 核心 CSS 文件 -->
	<link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<!-- 可选的Bootstrap主题文件（一般不用引入） -->
	<link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<!-- CSS
  ================================================== -->
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/inner.css' %}" />    
    <link rel="stylesheet" href="{% static 'styles/color.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/layout.css' %}" />
    

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

	<!-- this script use the rotate ball tag cloud, It adjust the tag between 20 and 30 -->
    <!-- <script type="text/javascript" src="{% static 'js/tagcloud.js' %}"></script> -->
    
</head>
{% endblock %}


<body>

<div id="bodychild">
	<div id="outercontainer">
	
    <!-- HEADER -->
        <div id="outerheader">
            <header id="top">

                    <div id="logo">
                        <a href="{% url 'blog:blog' %}"><img src="{% static 'images/logo.png' %}" alt=""/><h3 class="logofont">William's blog</h3><h4 class="logofont">made by pengjunjie (william valentine)</h4></a>
                    </div>

                    <section id="navigation">
                        <nav id="nav-wrap">
                            <ul id="topnav" class="sf-menu">
                                <li><a href="{% url 'blog:blog' %}">{% trans 'home' %} </a></li>
                                <li><a href="{% url 'blog:blog' %}">{% trans 'blog' %}</a></li>
                                <li><a href={% url 'blog:bookmark' %}>{% trans 'suggest url' %}</a></li>
                                <li><a href="#">{% trans 'appcenter' %}</a>
                                    <ul>
                                        <li><a href="{% url 'blog:appcategory'  3 %}">{% trans 'saasappcenter' %}</a></li>
                                        <li><a href="{% url 'blog:appcategory' 4 %}">{% trans 'h5appcenter' %}</a></li>
                                        <li><a href="#">{% trans 'toolcenter' %}</a>
                                            <ul>
                                                <li><a href="{% url 'blog:appcategory' 1 %}">{% trans 'Windows Tools' %}</a></li>
                                                <li><a href="{% url 'blog:appcategory' 2 %}">{% trans 'Mac Tools' %}</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'blog:contact' %}">{% trans 'contactme' %}</a></li>
                                <li><a href="http://wedding.pengjunjie.com">{% trans 'wedding' %}</a></li>
                            </ul><!-- topnav -->
                           
                            <div class="clear"></div>
                        </nav><!-- nav -->	
                    </section>
            
                <div class="clear"></div>
            </header>
        </div>
        <!-- END HEADER -->
        
    {% block content %}{% endblock %}     
           
        <!-- FOOTER -->
        <footer id="footer">
        	
            <!-- FOOTER SIDEBAR -->
            <div id="outerfootersidebar">
                <div class="container">
                    <div id="footersidebar" class="row"> 

                        <div id="footcol1"  class="three columns">
                            <ul>
                                <li class="widget-container">
                                    <h2 class="widget-title">{% trans 'About William blog' %}</h2>
                                    <ul class="rp-widget">
                                        <li>
                                            <img  alt="" src="{% static 'images/content/logo_50_50.png' %}">
                                            <h3><a href="#">william blog</a></h3>
                                            <span class="smalldate">November 18, 2015</span>
                                            <p>william blog power by <a href="https://github.com/yourwilliam/melonblog">melon blog</a> for my melon baby.</p>
                                            <a href="https://github.com/yourwilliam/melonblog" class="more">Read Melon Blog</a>
                                            <span class="clear"></span>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div id="footcol2"  class="three columns">
                            <ul>
                                <li class="widget-container">
                                    <h2 class="widget-title">{% trans 'Favourite Site' %}</h2>
									<ul class="flickr">
                                    	<li><a href="http://www.hansap.com" target="_Blank"><img src="{% static 'images/content/g1.png' %}" alt="" /></a></li>
                                        <li><a href="https://www.topcoder.com/" target="_Blank"><img src="{% static 'images/content/g2.png' %}" alt="" /></a></li>
                                        <li><a href="http://toutiao.io/" target="_Blank"><img src="{% static 'images/content/g3.png' %}" alt="" /></a></li>
                                        <li><a href="http://www.techtarget.com.cn/" target="_Blank"><img src="{% static 'images/content/g4.png' %}" alt="" /></a></li>
                                        <li><a href="http://www.oschina.net/" target="_Blank"><img src="{% static 'images/content/g5.png' %}" alt="" /></a></li>
                                        <li><a href="https://getpocket.com" target="_Blank"><img src="{% static 'images/content/g6.png' %}" alt="" /></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div id="footcol3"  class="three columns">
                            <ul>
                                <li class="widget-container">
                                    <h2 class="widget-title">{% trans 'Our Categories' %}</h2>
                                    <ul class="list">
                                        <li><a href="{% url 'blog:blog' %}">{% trans 'home' %}</a></li>
                                        <li><a href="{% url 'blog:blog' %}">{% trans 'blog' %}</a></li>
                                        <li><a href="{% url 'blog:bookmark' %}">{% trans 'suggest url' %}</a></li>
                                        <li><a href="#">{% trans 'appcenter' %}</a></li>
                                        <li><a href="{% url 'blog:contact' %}">{% trans 'contactme' %}</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div id="footcol4"  class="three columns">
                            <ul>
                                <li class="widget-container">
                                    <h2 class="widget-title">{% trans 'contact me' %}</h2>
                                    <ul class="sn">
                                        <li><a href="https://twitter.com/yourwilliam" title="Twitter"><span class="icon-img twitter"></span></a></li>
                                        <li><a href="https://www.facebook.com/yourwilliam" title="Facebook"><span class="icon-img facebook"></span></a></li>
                                        <li><a href="https://plus.google.com/u/0/103856410165086313285" title="Google+"><span class="icon-img google"></span></a></li>
                                        <li><a href="{% url 'blog:latestentriesfeed' %}" title="RSS"><span class="icon-img rss"></span></a></li>
                                        <li><a href="http://pinterest.com" title="Pinterest"><span class="icon-img pinterest"></span></a></li>
                                    </ul> 
                              </li>
                            </ul>
                        </div>
                        <div class="clear"></div>
                 
                    </div>
                </div>
            </div>
            <!-- END FOOTER SIDEBAR -->
            
            <!-- COPYRIGHT -->
            <div id="outercopyright">
                <div class="container">
                    <div id="copyright">
                    	{% trans 'Copyright' %}
                    	<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1260142205'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1260142205%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
                    </div>
                </div>
            </div>
            <!-- END COPYRIGHT -->
        </footer>
        <!-- END FOOTER -->
        <div class="clear"></div><!-- clear float --> 
	</div><!-- end outercontainer -->
</div><!-- end bodychild -->

{% block javascript %}
<!-- ////////////////////////////////// -->
<!-- //      Javascript Files        // -->
<!-- ////////////////////////////////// -->
<script type="text/javascript" src="{% static 'js/jquery-1.7.1.min.js' %}"></script>

<!-- jQuery Superfish -->
<script type="text/javascript" src="{% static 'js/hoverIntent.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/superfish.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/supersubs.js' %}"></script>


<!-- jQuery Dropdown Mobile -->
<script type="text/javascript" src="{% static 'js/tinynav.min.js' %}"></script>

<!-- Custom Script -->
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

{% endblock %}
</body>
</html>

blog/templates/common/base_blog.html
{% extends "common/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}        
        <!-- BEFORE CONTENT -->
        <div id="outerbeforecontent">
        	<div class="container">
            <div class="row">
                <div id="beforecontent" class="twelve columns">
                    <h1 class="pagetitle">{% trans 'William Blog' %} </h1>
                    <span class="pagedesc">{% trans 'William Blog Abstract' %}</span>
                    
                    <a href="#" class="button">{% trans 'william blog' %}</a>
                    
                </div>
            </div>
            </div>
        </div>
        <!-- END BEFORE CONTENT -->

        <!-- MAIN CONTENT -->
        
        <div id="outermain">
        	<div class="container">
                <div class="row">
           
           			
                    <section id="maincontent" class="eight columns positionleft">
                    	<div class="padcontent">
						{% block maincontent %}{% endblock %}                 
                        </div>
                    </section>

                    
                    {% block sidebar %}
                    <aside id="sidebar" class="four columns">
                    	<div class="padsidebar">
                        <ul>
                            <li class="widget-container">
                                <h2 class="widget-title">{% trans 'Search' %}</h2>
                                <form action="#" id="searchform" method="get">
                                    <div class="bgsearch">
                                    <input type="text" value="" id="s" name="s"> 
                                    <input type="submit" value="" class="searchbutton">
                                    </div>
                                </form>
                            </li>
                            <li class="widget-container">
                                <h2 class="widget-title">{% trans 'Categories' %}</h2>
                                <ul>
                                {% for category in catagory_list %}
                                	<li><a href="{% url 'blog:category' category.id %}">{{ category.title }}({{category.entrynum}})</a></li>
                                {% endfor %}
                                </ul>
                            </li>
                            <li class="widget-container">
                                <h2 class="widget-title">{% trans 'Latest Post' %}</h2>
                                <ul class="rp-widget">
                                	{% for post in latest_post %}
                                		<li>
		                                    <div class="postimg"><img src="{% static 'images/content/lp1.gif' %}" alt="" /></div>
		                                    <h3><a href="{% url 'blog:single' post.id %}">{{ post.title }}</a></h3>
		                                    <span class="smalldate">{{ post.publication_date }}</span>
		                                    <span class="clear"></span>
                                    </li>
                                	{% endfor %}
                                </ul>
                            </li>
                        </ul>
                        <div>
                        <h2 class="widget-title">{% trans 'Tag list' %}</h2>
                        <div class="tagcloud">
                        {% for tag in tag_list %}
                        	<a href="{% url 'blog:tags' tag.id %}" class="tagitem btn btn-success btn-xs">{{ tag.name }}</a>
                        {% endfor %}
                        </div>
						</div>
	                  </div>
                    </aside>
               		{% endblock %}  
                </div>
            </div>
        </div>
        <!-- END MAIN CONTENT -->
 
 {% endblock %}